### PR TITLE
Create fr_fr.json

### PR DESCRIPTION
**Pull request by HollishKid**

### CODE REVIEW

**Review by K0LALA — APPROVED** [review]
Traduction is fine to me 👍

**Review by K0LALA — CHANGES_REQUESTED** [review]
This is the updated version
[fr_fr.json.txt](https://github.com/FTBTeam/FTB-Teams/files/12463161/fr_fr.json.txt)

**Comment by desht** [comment]
That file appears to be empty?

**Comment by K0LALA** [comment]
> That file appears to be empty?

yes my bad, this one is better I think, you just need to remove the .txt at the end and replace it with .json, because apparently Github doesn't support json files
[fr_fr.txt](https://github.com/FTBTeam/FTB-Teams/files/12463758/fr_fr.txt)

**Comment by desht** [comment]
Thanks.  I'll need to close this PR and add the translation in manually (will credit you both in the changelog though)

**Review by desht — APPROVED** [review]

**Pull request closed without merging**
